#creating docker compose file to programmatically start all containers in the same network and perfrom health checks

services:
  #creating db service
  database:
    image: lorenzofaccio/datab-x86:0.0.3
    ports:
      - "3306:3306"
    volumes:
      - geniz-data:/var/lib/mysql

    #setup healthcheck to prevent backend to start before db
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 3s
      retries: 9

    #setup env variables for the db
    environment:
      MYSQL_ROOT_PASSWORD: sample_passw!345


  #creating backend instance
  backend:
    image: lorenzofaccio/backend-x86:0.0.3
    ports:
      - "24987:8080"

    #specify bond mounts for exported txts
    volumes: 
      - ~/Documents/GenIz_txt:/exported_quizzes

    #defining local model
    models:
      - llm

    environment:
      MODEL_URL: 'http://model-runner.docker.internal/v1/chat/completions'
      LLM_MODEL: 'ai/qwen2.5:3B-Q4_K_M'
      DB_URL: jdbc:mysql://database:3306/geniz
      DB_PASSWORD: sample_passw!345
      DB_USER: root

      #setting up env to tell spring security to communicate with Auth0 as localhost:24978 instead of 8080 (internal port)
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_AUTH0_REDIRECT_URI: "http://localhost:24987/login/oauth2/code/auth0"
      SERVER_FORWARD_HEADERS_STRATEGY: native

    depends_on:
      database:
        condition: service_healthy


  #define frontend services 
  frontend: 
    image: lorenzofaccio/frontend-x86:0.0.3
    ports: 
     - "24991:5173"

#define local model and model contex size
models:
    llm:
      model: ai/qwen2.5:3B-Q4_K_M
      context_size: 16384

#specify volumes
volumes:
  geniz-data:
