spring.application.name=genIz

#setting up debug mode 
logging.level.org.springframework.security=debug
logging.level.org.springframework.web=debug

#Oauth2 setting to establish connections with the identity provider (Auth0 & Google)

#client-id, used to identify the Auth0 account, it's a public resource 
spring.security.oauth2.client.registration.auth0.client-id=C7IuQAe9lzqN4h98p1EFYDWswmyTAPGF

#since this application is a public client, no client-secret is needed
# spring.security.oauth2.client.registration.auth0.client-secret=none

#setting up the authentication method to be none, telling spring to use PKCE instead of the client secret 
spring.security.oauth2.client.registration.auth0.client-authentication-method=none

#start the connection with an authorization_code to enable the PKCE workflow 
spring.security.oauth2.client.registration.auth0.authorization-grant-type=authorization_code

#explicitly stating what the application is requesting
spring.security.oauth2.client.registration.auth0.scope=openid,profile,email

#callback url that recieves the authorization_code that will be used to retrieve the access token 
spring.security.oauth2.client.registration.auth0.redirect-uri=http://localhost:8080/login/oauth2/code/auth0

#general identity provider endpoint that will be used to find the needed provier endpoint to exchange information
spring.security.oauth2.client.provider.auth0.issuer-uri=https://dev-83b8o2lqqi2gbapm.eu.auth0.com/


#modifyng time to live of the JSESSIONID to allow persitance for x days even after the browes tab is closed 
#server.servlet.session.cookie.max-age=7d

#server.servlet.session.timeout=7d

#adding to the application the ability to read .env file like .properties fields
spring.config.import=file:.env[.properties]
